FROM {{ image }}

# disable space check in pacman
RUN sed -i '/CheckSpace/d' /etc/pacman.conf

# FYI: ldns includes drill
RUN pacman --noconfirm -Syu --needed git vi neovim man man-pages sudo \
                                      base-devel pkgfile ldns

# build man database
RUN mandb

# initialize pkgfile database
RUN pkgfile -u

{{ yay_install }}

RUN sudo -u build-user yay --noconfirm -Syu --needed {{ arch_pkgs }}

