FROM docker.io/golang:1.26.1

# https://github.com/anacrolix/torrent?tab=readme-ov-file#command-packages
# last dependency check 2026-03-14
RUN go install github.com/anacrolix/torrent/cmd/torrent@v1.61.0
