FROM docker.io/golang:1.24.2

# https://github.com/anacrolix/torrent?tab=readme-ov-file#command-packages
# last dependency check 2025-04-06
RUN go install github.com/anacrolix/torrent/cmd/torrent@v1.58.1
