FROM docker.io/golang:1.25.3

# https://github.com/anacrolix/torrent?tab=readme-ov-file#command-packages
# last dependency check 2025-11-03
RUN go install github.com/anacrolix/torrent/cmd/torrent@v1.59.1
